# Generated by Django 2.2.7 on 2020-01-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200122_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaprice',
            name='preparation_time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
