# Generated by Django 2.2.7 on 2020-01-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200123_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total_time',
            field=models.IntegerField(null=True),
        ),
    ]
