# Generated by Django 2.2.7 on 2020-01-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200124_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='preparation_time',
            field=models.IntegerField(null=True),
        ),
    ]
