# Generated by Django 2.2.7 on 2020-01-24 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200124_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order'),
        ),
    ]
